name = "CC8"
uuid = "3298a269-ba8c-4eac-a982-8b2cf2db77a8"
authors = ["Ivan Melchor <ifmelchor@unrn.edu.ar> and contributors"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"

[compat]
ProgressBars = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
